<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Select_Year</name>
   <tag></tag>
   <elementGuidId>dea2aef9-1b0a-456a-a191-1d2ed5104e45</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//*[@id=&quot;__next&quot;]/div[1]/div/div/div/div[2]/div/div[2]/div/div/div/div[2]/div/div/div/div/div[2]/div/div[1]/div/select[2]</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
